---
DEFAULT_BRANCH: main
VALIDATE_ALL_CODEBASE: false
SPELL_CSPELL_FILTER_REGEX_INCLUDE: (.*\.md)
FILTER_REGEX_INCLUDE: (.*\.yml|.*\.yaml|.*\.md|.*\.json)

ENABLE_LINTERS:
  - SPELL_CSPELL
  - YAML_YAMLLINT
  - REPOSITORY_SECRETLINT
